from isaacgym import gymapi
from pathlib import Path

def get_obj_dict(GymURDFAsset, scene, cfg):
    objects = {'block': [GymURDFAsset('assets/block.urdf', scene, 
                    shape_props=cfg['object']['shape_props'], 
                    rb_props=cfg['object']['rb_props'],
                    asset_options=cfg['object']['asset_options'],
                    assets_root=Path('config')), gymapi.Vec3(-0.4, -0.4, 1.1),gymapi.Vec3(-0.3, -0.4, 1.5), gymapi.Quat(0, 0, 0, 1)], 
                'disc': [GymURDFAsset('assets/disc.urdf', scene, 
                    shape_props=cfg['object']['shape_props'], 
                    rb_props=cfg['object']['rb_props'],
                    asset_options=cfg['object']['asset_options'],
                    assets_root=Path('config')), gymapi.Vec3(-0.3, -0.4, 1.1),gymapi.Vec3(-0.3, -0.4, 1.5), gymapi.Quat(0, 0, 0, 1)], 
                # 'heart': [GymURDFAsset('assets/heart.urdf', scene, 
                #     shape_props=cfg['object']['shape_props'], 
                #     rb_props=cfg['object']['rb_props'],
                #     asset_options=cfg['object']['asset_options'],
                #     assets_root=Path('config')),gymapi.Vec3(-0.3, -0.4, 1.5), gymapi.Quat(0, 0, 0, 1)],
                'hexagon': [GymURDFAsset('assets/hexagon.urdf', scene, 
                    shape_props=cfg['object']['shape_props'], 
                    rb_props=cfg['object']['rb_props'],
                    asset_options=cfg['object']['asset_options'],
                    assets_root=Path('config')), gymapi.Vec3(-0.2, -0.4, 1.1),gymapi.Vec3(-0.3, -0.4, 1.5), gymapi.Quat(0, 0, 0, 1)],
                'parallelogram': [GymURDFAsset('assets/parallelogram.urdf', scene, 
                    shape_props=cfg['object']['shape_props'], 
                    rb_props=cfg['object']['rb_props'],
                    asset_options=cfg['object']['asset_options'],
                    assets_root=Path('config')), gymapi.Vec3(-0.1, -0.4, 1.1),gymapi.Vec3(-0.3, -0.4, 1.5), gymapi.Quat(0, 0, 0, 1)],
                'semicircle': [GymURDFAsset('assets/semicircle.urdf', scene, 
                    shape_props=cfg['object']['shape_props'], 
                    rb_props=cfg['object']['rb_props'],
                    asset_options=cfg['object']['asset_options'],
                    assets_root=Path('config')), gymapi.Vec3(0, -0.4, 1.1),gymapi.Vec3(-0.3, -0.4, 1.5), gymapi.Quat(0, 0, 0, 1)],
                'shuriken': [GymURDFAsset('assets/shuriken.urdf', scene, 
                    shape_props=cfg['object']['shape_props'], 
                    rb_props=cfg['object']['rb_props'],
                    asset_options=cfg['object']['asset_options'],
                    assets_root=Path('config')), gymapi.Vec3(0.1, -0.4, 1.1),gymapi.Vec3(-0.3, -0.4, 1.5), gymapi.Quat(0, 0, 0, 1)],
                'star': [GymURDFAsset('assets/star.urdf', scene, 
                    shape_props=cfg['object']['shape_props'], 
                    rb_props=cfg['object']['rb_props'],
                    asset_options=cfg['object']['asset_options'],
                    assets_root=Path('config')), gymapi.Vec3(-0.4, -0.3, 1.1),gymapi.Vec3(-0.3, -0.4, 1.5), gymapi.Quat(0, 0, 0, 1)],
                'trapezium': [GymURDFAsset('assets/trapezium.urdf', scene, 
                    shape_props=cfg['object']['shape_props'], 
                    rb_props=cfg['object']['rb_props'],
                    asset_options=cfg['object']['asset_options'],
                    assets_root=Path('config')), gymapi.Vec3(-0.4, -0.2, 1.1),gymapi.Vec3(-0.3, -0.4, 1.5), gymapi.Quat(0, 0, 0, 1)],
                'triangle': [GymURDFAsset('assets/triangle.urdf', scene, 
                    shape_props=cfg['object']['shape_props'], 
                    rb_props=cfg['object']['rb_props'],
                    asset_options=cfg['object']['asset_options'],
                    assets_root=Path('config')), gymapi.Vec3(-0.4, -0.1, 1.1),gymapi.Vec3(-0.3, -0.4, 1.5), gymapi.Quat(0, 0, 0, 1)],
                }

    return objects